export const CHARACTERS_ACTION_TYPES = {
  FETCH_CHARACTERS_START: "characters/FETCH_CHARACTERS_START",
  FETCH_CHARACTERS_SUCCESS: "characters/FETCH_CHARACTERS_SUCCESS",
  FETCH_CHARACTERS_FAILED: "characters/FETCH_CHARACTERS_FAILED",
  FETCH_CHARACTERS_INFO_START: "characters/FETCH_CHARACTERS_INFO_START",
  FETCH_CHARACTERS_INFO_SUCCESS: "characters/FETCH_CHARACTERS_INFO_SUCCESS",
  FETCH_CHARACTERS_INFO_FAILED: "characters/FETCH_CHARACTERS_INFO_FAILED",
  SET_CHARACTERS_PAGE: "characters/SET_CHARACTERS_PAGE",
  SET_CHARACTERS_FILTER: "characters/SET_CHARACTERS_FILTER",
  CLEAR_CHARACTERS: "characters/CLEAR_CHARACTERS"
};
